# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txLkP9F9TVIy2-Lmk4AVR6ApOKcjn8Vn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

df = pd.read_csv("/content/Palo Alto Networks.csv")

df.head()

df.info()

df.describe()

df.isnull().sum()

df.drop_duplicates(inplace=True)

"""**Promotion Gap** **Ratio**"""

df['PromotionGapRatio']=(
    df['YearsSinceLastPromotion']/(df['YearsAtCompany']+1)
)

df['RoleStagnationIndex'] =(
    df['YearsInCurrentRole'] /
    (df['YearsAtCompany'] + 1)
)

df['TrainingIntensityScore'] = (
    df['TrainingTimesLastYear'] /
    (df['YearsAtCompany'] + 1)
)

df['ManagerStability'] = (
    df['YearsWithCurrManager'] /
    (df['YearsAtCompany'] + 1)
)

le = LabelEncoder()

cat_cols = [
    'BusinessTravel',
    'Department',
    'EducationField',
    'Gender',
    'JobRole',
    'MaritalStatus',
    'OverTime'
]

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

features = [
    'PromotionGapRatio',
    'RoleStagnationIndex',
    'TrainingIntensityScore',
    'ManagerStability',
    'YearsAtCompany',
    'YearsInCurrentRole',
    'YearsSinceLastPromotion',
    'JobLevel',
    'MonthlyIncome'
]

scaler = StandardScaler()
X = scaler.fit_transform(df[features])

wcss = []

for i in range(1,11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

plt.plot(range(1,11), wcss)
plt.xlabel("Clusters")
plt.ylabel("WCSS")
plt.title("Elbow Method")
plt.show()

kmeans = KMeans(n_clusters=5, random_state=42)

df['Cluster'] = kmeans.fit_predict(X)

df.groupby('Cluster')[features].mean()

conditions = [
    (df['PromotionGapRatio'] < 0.3),
    (df['PromotionGapRatio'] >= 0.3) &(df['PromotionGapRatio']<0.7),
    (df['PromotionGapRatio'] >= 0.7)&(df['PromotionGapRatio']<1.0),
     (df['PromotionGapRatio'] >= 1.0)]
values = ['Low', 'Medium', 'High', 'Very High']

df['PromotionGapRisk'] = np.select(
    conditions,
    values, default='Unknown'
)

retention_df = df[
    (df['Attrition'] == 0) &
    (df['PromotionGapRisk'] == 'High')
]



"""**EDA VISUAL**"""

sns.countplot(x='Attrition', data = df)
plt.show()

sns.countplot(x= 'Cluster', data = df)
plt.show()

sns.scatterplot(
    x='MonthlyIncome',
    y='PromotionGapRatio',
    hue='Cluster',
    data=df
)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st
import pandas as pd
import plotly.express as px

df = pd.read_csv("final_employee_data.csv")

st.title("Career Progression Dashboard")

department = st.selectbox(
    "Select Department",
    df['Department'].unique()
)

filtered_df = df[
    df['Department'] == department
]

fig = px.scatter(
    filtered_df,
    x='MonthlyIncome',
    y='PromotionGapRatio',
    color='Cluster'
)

st.plotly_chart(fig)

